stages:
  generate_data:
    cmd: poetry run python src/generate_data.py --params params.yaml
    deps:
      - src/generate_data.py
      - params.yaml
    outs:
      - data/raw/open_rate_data.csv

  prepare_data:
    cmd: poetry run python src/prepare_data.py --params params.yaml
    deps:
      - src/prepare_data.py
      - params.yaml
      - data/raw/open_rate_data.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train_model:
    cmd: poetry run python src/train.py --params params.yaml
    deps:
      - src/train.py
      - params.yaml
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/logistic_regression_model.joblib